# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20171112_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
