# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_todo_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='modified',
            field=models.BooleanField(default=0),
        ),
    ]
